---
- name: Check for {{ item.version }}
  stat:
    path: '{{ pyenv.path }}/versions/{{ item.version }}'
  register: python
  ignore_errors: yes

- name: Install python {{ item.version }}
  raw: 'PYENV_ROOT={{ pyenv.path }} {{ pyenv.path }}/bin/pyenv install {{ item.version }}'
  notify: rehash
  when: not python.stat.exists
